#!/usr/bin/env python3
"""Baseline accuracy report for the rebuilt datasets (Phase 1 deliverable).

    python3 -m ml.evaluate_baseline [--out ml/out]

Reads <out>/kbo_dataset.csv, <out>/wnba_dataset.csv (from the build_dataset
scripts) and, if present, <out>/kbo_replay.csv / <out>/wnba_replay.csv /
<out>/nfl_replay_summary.csv, and writes <out>/baseline_report.md plus
<out>/baseline_<sport>_by_prop.csv. Metric definitions: ml/common/metrics.py.

Reproducing the numbers in ML_PLAN.md section 4 exactly requires building the
datasets at the audit ref:  --ref 25137d4d6  (later refs add more days).
"""
from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from ml.common.metrics import markdown_table, summarize
from ml.common.util import DEFAULT_OUT, write_csv

# Early KBO batter snapshots (2026-03-31..04-19) predate the odds_type field and
# only carried standard lines, so "unknown" counts as standard (as in ML_PLAN.md).
STANDARD = ("standard", "unknown")

COLS = ["prop", "n", "days", "mae_proj", "mae_line", "bias_proj", "dir_hit_rate", "n_dir",
        "rec_hit_rate", "n_rec", "base_rate_over", "pct_proj_over"]


def load(path: Path, numeric=("line", "projection", "actual")) -> list[dict]:
    rows = []
    with path.open(encoding="utf-8") as handle:
        for row in csv.DictReader(handle):
            try:
                for key in numeric:
                    row[key] = float(row[key])
            except (TypeError, ValueError):
                continue
            rows.append(row)
    return rows


def section(title: str, rows: list[dict], note: str = "") -> tuple[str, list[dict]]:
    by_prop = sorted(summarize(rows, ["prop"]), key=lambda r: -r["n"])
    total = summarize([dict(r, prop="ALL") for r in rows], ["prop"])
    text = [f"### {title}", ""]
    if note:
        text += [note, ""]
    text += [markdown_table(by_prop, COLS), "", markdown_table(total, COLS), ""]
    return "\n".join(text), by_prop + total


def replay_section(title: str, rows: list[dict], col: str) -> str:
    usable = [dict(r, projection=float(r[col])) for r in rows if r.get(col) not in (None, "")]
    if not usable:
        return f"### {title}\n\n(no replay rows)\n"
    cols = ["prop", "n", "days", "mae_proj", "mae_line", "bias_proj", "dir_hit_rate", "n_dir"]
    by_prop = sorted(summarize(usable, ["prop"]), key=lambda r: -r["n"])
    return "\n".join([f"### {title}", "", markdown_table(by_prop, cols), ""])


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = ap.parse_args(argv)
    out = args.out
    parts = ["# Phase 1 baseline report", "",
             "Generated by `python3 -m ml.evaluate_baseline`. Standard lines only unless noted.", ""]
    for sport in ("kbo", "wnba"):
        path = out / f"{sport}_dataset.csv"
        if not path.exists():
            parts.append(f"### {sport.upper()}\n\n{path.name} missing; run `python3 -m ml.{sport}.build_dataset`.\n")
            continue
        rows = [r for r in load(path) if r.get("odds_type") in STANDARD]
        stats_path = out / f"{sport}_dataset_stats.json"
        ref = json.loads(stats_path.read_text()).get("ref", "?") if stats_path.exists() else "?"
        text, table = section(f"{sport.upper()} standard lines", rows, f"Dataset ref `{ref[:12]}`.")
        parts.append(text)
        write_csv(out / f"baseline_{sport}_by_prop.csv", table, COLS)
        replay = out / f"{sport}_replay.csv"
        if replay.exists():
            rrows = [r for r in load(replay) if r.get("odds_type") in STANDARD]
            parts.append(replay_section(
                f"{sport.upper()} formula replay (Python, point-in-time) vs actual", rrows, "replay_projection"))
        parity_path = out / f"{sport}_replay_parity.json"
        if parity_path.exists():
            months = json.loads(parity_path.read_text()).get("_by_month_share_within_0.05", {})
            recs = [{"month": k, **v} for k, v in months.items()]
            if recs:
                parts += ["Replay parity with published projections (share within 0.05, by month; "
                          "older months used older live formulas):", "", markdown_table(recs, ["month", "n", "share"]), ""]
    nfl = out / "nfl_replay_summary.csv"
    if nfl.exists():
        with nfl.open(encoding="utf-8") as handle:
            recs = list(csv.DictReader(handle))
        parts += ["### NFL (replay on nflverse; no historical lines exist)", "",
                  markdown_table(recs, list(recs[0].keys())) if recs else "(empty)", ""]
    report = "\n".join(parts)
    (out / "baseline_report.md").write_text(report + "\n", encoding="utf-8")
    print(report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
