#!/usr/bin/env python3
"""
Generate prizepicks_props.json — merges PrizePicks lines with game log data
to produce player cards with hit rates, recent logs, and projections.
"""
import csv
import json
import os
from collections import defaultdict

BASE = os.path.dirname(os.path.abspath(__file__))
PUBLIC_DATA = os.path.join(BASE, "kbo-props-ui", "public", "data")

PP_NAME_ALIASES = {
    "hyeok park chan": "Park Chan-hyeok",
}

def name_signature(name):
    """Word-order agnostic normalized signature for robust name matching."""
    return " ".join(sorted(normalize(name).split()))

def load_pitcher_aliases():
    """Load shared PrizePicks pitcher aliases generated by projection pipeline."""
    path = os.path.join(BASE, "Pitchers-Data", "prizepicks_pitcher_name_map.json")
    if not os.path.exists(path):
        return {}
    try:
        with open(path) as f:
            data = json.load(f)
        return {normalize(k): v for k, v in data.get("map", data).items() if isinstance(k, str) and isinstance(v, str) and k and v}
    except Exception:
        return {}

def load_odds():
    path = os.path.join(BASE, "KBO-Odds", "KBO_odds_2025.csv")
    if not os.path.exists(path):
        return []
    with open(path) as f:
        return list(csv.DictReader(f))

def load_pitcher_logs():
    public_path = os.path.join(PUBLIC_DATA, "pitcher_logs.json")
    source_path = os.path.join(BASE, "Pitchers-Data", "pitcher_logs.json")
    candidates = [p for p in (public_path, source_path) if os.path.exists(p)]
    if not candidates:
        return []
    path = max(candidates, key=os.path.getmtime)
    with open(path) as f:
        return json.load(f)

def load_batter_logs():
    path = os.path.join(PUBLIC_DATA, "prop_results.json")
    if not os.path.exists(path):
        return {"stats": []}
    with open(path) as f:
        return json.load(f)

def load_projections():
    k_path = os.path.join(PUBLIC_DATA, "strikeout_projections.json")
    b_path = os.path.join(PUBLIC_DATA, "batter_projections.json")
    k_proj, b_proj = {}, {}
    if os.path.exists(k_path):
        with open(k_path) as f:
            d = json.load(f)
        for p in d.get("projections", []):
            if p.get("name"):
                k_proj[p["name"]] = p
                # Also index by pp_name so lookup works with PrizePicks display names
                if p.get("pp_name"):
                    k_proj.setdefault(p["pp_name"], p)
    if os.path.exists(b_path):
        with open(b_path) as f:
            d = json.load(f)
        for p in d.get("projections", []):
            if p.get("name"):
                key = (p["name"], p.get("prop", ""))
                b_proj[key] = p
    return k_proj, b_proj

def normalize(name):
    """Normalize for fuzzy matching — lowercase, strip accents/diacritics, treat hyphens as spaces."""
    import unicodedata
    n = unicodedata.normalize("NFD", name)
    n = "".join(c for c in n if unicodedata.category(c) != "Mn")
    # Treat hyphens and underscores as spaces so "Song Seung-ki" matches "Song Seung Ki"
    n = n.replace("-", " ").replace("_", " ")
    # Normalize all quote variants (smart quotes, backtick) to simple apostrophe
    n = n.replace("\u2018", "'").replace("\u2019", "'").replace("`", "'")
    # Collapse multiple spaces
    n = " ".join(n.split())
    return n.lower().strip()

def _parse_date(d):
    """Parse MM/DD/YYYY or YYYY-MM-DD to a sortable tuple."""
    try:
        if '/' in d:
            parts = d.split('/')
            return (int(parts[2]), int(parts[0]), int(parts[1]))
        elif '-' in d:
            parts = d.split('-')
            return (int(parts[0]), int(parts[1]), int(parts[2]))
    except (ValueError, IndexError):
        pass
    return (0, 0, 0)

def build_pitcher_card(name, props, pitcher_logs_by_name, k_proj, display_name=None):
    logs = pitcher_logs_by_name.get(name, [])
    # Sort by date descending (handles MM/DD/YYYY correctly)
    logs.sort(key=lambda x: _parse_date(x.get("Date", "")), reverse=True)

    games = []
    for g in logs:
        games.append({
            "date": g.get("Date", ""),
            "opp": g.get("Opp", ""),
            "ip": g.get("IP", 0),
            "so": g.get("SO", 0),
            "er": g.get("ER", 0),
            "ha": g.get("HA", 0),
            "bb": g.get("BB", 0),
            "era": g.get("ERA", 0),
            "whip": g.get("WHIP", 0),
            "outs": g.get("PitOuts", 0),
        })

    card = {
        "name": name,
        "team": props[0]["team"],
        "opponent": props[0]["vs"],
        "type": "pitcher",
        "props": [],
        "games": games[:15],  # last 15 games
    }

    # Look up projection using multiple name variants
    _lookup_names = [name]
    if display_name and display_name != name:
        _lookup_names.append(display_name)
    _lookup_names.append(name_signature(name))
    proj = {}
    for _n in _lookup_names:
        proj = k_proj.get(_n, {})
        if proj:
            break
    # Also try normalized name-signature against k_proj keys
    if not proj:
        _sig = name_signature(name)
        for k, v in k_proj.items():
            if name_signature(k) == _sig:
                proj = v
                break

    if proj:
        card["projection_so"] = proj.get("projection")
        card["so_per_ip"] = proj.get("so_per_ip")
        card["ip_per_g"] = proj.get("ip_per_g")
        card["proj_rating"] = proj.get("rating")
        card["proj_rec"] = proj.get("recommendation")

    # Build a dict of prop-type-specific projections from k_proj
    # k_proj may have multiple entries per pitcher (one per prop type)
    _prop_proj = {}
    for _n in _lookup_names:
        for k, v in k_proj.items():
            if name_signature(k) == name_signature(_n):
                prop_type = v.get("prop", "Strikeouts")
                _prop_proj.setdefault(prop_type, v)

    _stat_to_prop = {
        "Pitcher Strikeouts": "Strikeouts",
        "Pitching Outs": "Pitching Outs",
        "Hits Allowed": "Hits Allowed",
        "Pitcher Hits Allowed": "Hits Allowed",
    }

    for p in props:
        stat = p["stat"]
        line = float(p["line"])

        if stat == "Pitcher Strikeouts":
            values = [g["so"] for g in games]
        elif stat == "Pitching Outs":
            values = [g["outs"] for g in games]
        elif stat in ("Hits Allowed", "Pitcher Hits Allowed"):
            values = [g["ha"] for g in games]
        else:
            continue

        total = len(values)
        over_count = sum(1 for v in values if v > line)
        push_count = sum(1 for v in values if v == line)
        under_count = total - over_count - push_count
        hit_rate = (over_count / total * 100) if total > 0 else 0
        avg_val = sum(values) / total if total > 0 else 0

        # Last 5, 10, 20
        l5 = values[:5]
        l10 = values[:10]
        l20 = values[:20]
        hr5 = (sum(1 for v in l5 if v > line) / len(l5) * 100) if l5 else 0
        hr10 = (sum(1 for v in l10 if v > line) / len(l10) * 100) if l10 else 0
        hr20 = (sum(1 for v in l20 if v > line) / len(l20) * 100) if l20 else 0

        # Get prop-specific projection
        stat_proj = _prop_proj.get(_stat_to_prop.get(stat, ""), {})
        proj_val = stat_proj.get("projection")

        card["props"].append({
            "stat": stat,
            "line": line,
            "avg": round(proj_val, 2) if proj_val is not None else round(avg_val, 2),
            "over": over_count,
            "under": under_count,
            "push": push_count,
            "total_games": total,
            "hit_rate_all": round(hit_rate, 1),
            "hit_rate_l5": round(hr5, 1),
            "hit_rate_l10": round(hr10, 1),
            "hit_rate_l20": round(hr20, 1),
            "recent_values": values[:10],
            "recommendation": stat_proj.get("recommendation"),
        })

    return card

def build_batter_card(name, props, batter_logs_by_name, b_proj):
    logs = batter_logs_by_name.get(name, [])
    # Sort by date descending (handles YYYY-MM-DD correctly)
    logs.sort(key=lambda x: _parse_date(x.get("date", "")), reverse=True)

    games = []
    for g in logs:
        games.append({
            "date": g.get("date", ""),
            "opp": g.get("opponent", ""),
            "h": g.get("h", 0),
            "r": g.get("r", 0),
            "rbi": g.get("rbi", 0),
            "hrr": g.get("hrr", 0),
            "tb": g.get("tb", 0),
        })

    card = {
        "name": name,
        "team": props[0]["team"],
        "opponent": props[0]["vs"],
        "type": "batter",
        "props": [],
        "games": games[:15],
    }

    for p in props:
        stat = p["stat"]
        line = float(p["line"])

        if stat == "Hits+Runs+RBIs":
            values = [g["hrr"] for g in games]
            key = "hrr"
        elif stat == "Total Bases":
            values = [g["tb"] for g in games]
            key = "tb"
        else:
            continue

        total = len(values)
        over_count = sum(1 for v in values if v > line)
        push_count = sum(1 for v in values if v == line)
        under_count = total - over_count - push_count
        hit_rate = (over_count / total * 100) if total > 0 else 0
        avg_val = sum(values) / total if total > 0 else 0

        l5 = values[:5]
        l10 = values[:10]
        l20 = values[:20]
        hr5 = (sum(1 for v in l5 if v > line) / len(l5) * 100) if l5 else 0
        hr10 = (sum(1 for v in l10 if v > line) / len(l10) * 100) if l10 else 0
        hr20 = (sum(1 for v in l20 if v > line) / len(l20) * 100) if l20 else 0

        # Get projection
        proj = b_proj.get((name, stat), {})

        card["props"].append({
            "stat": stat,
            "line": line,
            "avg": round(avg_val, 2),
            "over": over_count,
            "under": under_count,
            "push": push_count,
            "total_games": total,
            "hit_rate_all": round(hit_rate, 1),
            "hit_rate_l5": round(hr5, 1),
            "hit_rate_l10": round(hr10, 1),
            "hit_rate_l20": round(hr20, 1),
            "recent_values": values[:10],
            "projection": proj.get("projection"),
            "edge": proj.get("edge"),
            "rating": proj.get("rating"),
            "recommendation": proj.get("recommendation"),
        })

    return card

def main():
    odds = load_odds()
    pitcher_logs = load_pitcher_logs()
    batter_data = load_batter_logs()
    k_proj, b_proj = load_projections()

    # --- Filter for today's slate ---
    from datetime import datetime as _dt
    today_str = _dt.now().strftime("%m/%d/%Y")
    today_batters = set()
    today_pitchers = set()

    # Load PrizePicks pitcher aliases for name resolution
    pitcher_aliases = load_pitcher_aliases()
    # Build reverse alias map: canonical -> set of normalized aliases
    _reverse_aliases = defaultdict(set)
    for alias_norm, canonical in pitcher_aliases.items():
        _reverse_aliases[normalize(canonical)].add(alias_norm)

    # Batting stats (from Batters-Data)
    batting_path = os.path.join(BASE, "Batters-Data", "KBO_daily_batting_stats_2026.csv")
    if os.path.exists(batting_path):
        with open(batting_path) as f:
            reader = csv.DictReader(f)
            for row in reader:
                if row.get("DATE") == today_str:
                    today_batters.add(normalize(row["Name"].strip()))

    # Also add batters from today's batter projections (covers pre-game / stale CSV)
    batter_proj_path = os.path.join(PUBLIC_DATA, "batter_projections.json")
    if os.path.exists(batter_proj_path):
        with open(batter_proj_path) as f:
            bp = json.load(f)
            for proj in bp.get("projections", []):
                pp_name = proj.get("pp_name") or proj.get("name", "")
                if pp_name:
                    today_batters.add(normalize(pp_name))
                name = proj.get("name", "")
                if name:
                    today_batters.add(normalize(name))

    # Pitching stats (from daily CSV)
    pitching_path = os.path.join(BASE, "Pitchers-Data", "KBO_daily_pitching_stats.csv")
    if os.path.exists(pitching_path):
        with open(pitching_path) as f:
            reader = csv.DictReader(f)
            for row in reader:
                if row.get("Date") == today_str:
                    nm = normalize(row["Name"].strip())
                    today_pitchers.add(nm)
                    # Also add any known aliases of this pitcher
                    for alias in _reverse_aliases.get(nm, set()):
                        today_pitchers.add(alias)

    # Also add scheduled starters from player_names.csv (covers pre-game)
    starters_path = os.path.join(BASE, "Pitchers-Data", "player_names.csv")
    if os.path.exists(starters_path):
        with open(starters_path) as f:
            for row in csv.DictReader(f):
                nm = normalize(row.get("Player", "").strip())
                if nm:
                    today_pitchers.add(nm)
                    for alias in _reverse_aliases.get(nm, set()):
                        today_pitchers.add(alias)

    # Add all PrizePicks alias names so odds match
    for alias_norm, canonical in pitcher_aliases.items():
        canon_norm = normalize(canonical)
        if canon_norm in today_pitchers or alias_norm in today_pitchers:
            today_pitchers.add(alias_norm)
            today_pitchers.add(canon_norm)

    # Load park factors from batter projections
    park_factors = {}
    b_path = os.path.join(PUBLIC_DATA, "batter_projections.json")
    if os.path.exists(b_path):
        with open(b_path) as f:
            park_factors = json.load(f).get("park_factors", {})

    # Load starters to determine home teams
    home_map = {}
    starters_path = os.path.join(BASE, "Pitchers-Data", "player_names.csv")
    if os.path.exists(starters_path):
        teams = []
        with open(starters_path) as f:
            for row in csv.DictReader(f):
                teams.append(row["Team"])
        for i in range(0, len(teams), 2):
            away = teams[i]
            home = teams[i + 1] if i + 1 < len(teams) else None
            if home:
                home_map[away] = home
                home_map[home] = home

    # Index pitcher logs by name
    pitcher_logs_by_name = defaultdict(list)
    for log in pitcher_logs:
        pitcher_logs_by_name[log["Name"]].append(log)

    # Index batter logs by name
    batter_logs_by_name = defaultdict(list)
    for s in batter_data.get("stats", []):
        if s.get("type") == "batter":
            batter_logs_by_name[s["name"]].append(s)

    # Build fuzzy lookup for both
    norm_pitcher = {normalize(n): n for n in pitcher_logs_by_name}
    sig_pitcher = {name_signature(n): n for n in pitcher_logs_by_name}
    norm_batter = {normalize(n): n for n in batter_logs_by_name}
    sig_batter = {name_signature(n): n for n in batter_logs_by_name}

    # Group odds by player, but only include if in today's slate
    by_player = defaultdict(list)
    for o in odds:
        name = o["Name"].strip()
        norm_name = normalize(name)
        stat = o["Stat"]
        # Only include if player is in today's logs (normalized)
        if (
            (stat in ("Pitcher Strikeouts", "Pitching Outs", "Hits Allowed", "Pitcher Hits Allowed") and norm_name in today_pitchers)
            or (stat in ("Hits+Runs+RBIs", "Total Bases") and norm_name in today_batters)
        ):
            by_player[name].append({
                "stat": stat,
                "line": o["Prizepicks"],
                "vs": o["Versus"],
                "team": o["Team"],
            })

    cards = []
    for player_name, props in by_player.items():
        is_pitcher = any(
            p["stat"] in ("Pitcher Strikeouts", "Pitching Outs", "Hits Allowed", "Pitcher Hits Allowed")
            for p in props
        )
        is_batter = any(p["stat"] in ("Hits+Runs+RBIs", "Total Bases") for p in props)

        nn = normalize(player_name)
        aliased_name = PP_NAME_ALIASES.get(nn)

        if is_pitcher:
            shared_alias_name = pitcher_aliases.get(nn)
            sig_name = sig_pitcher.get(name_signature(player_name))
            if shared_alias_name:
                log_name = shared_alias_name
            elif aliased_name:
                log_name = aliased_name
            elif nn in norm_pitcher:
                log_name = norm_pitcher[nn]
            elif sig_name:
                log_name = sig_name
            else:
                log_name = player_name
            pitcher_props = [
                p for p in props
                if p["stat"] in ("Pitcher Strikeouts", "Pitching Outs", "Hits Allowed", "Pitcher Hits Allowed")
            ]
            card = build_pitcher_card(log_name, pitcher_props, pitcher_logs_by_name, k_proj, display_name=player_name)
            card["name"] = player_name  # Use PP display name
            cards.append(card)

        if is_batter:
            sig_name_b = sig_batter.get(name_signature(player_name))
            if aliased_name and normalize(aliased_name) in norm_batter:
                log_name = norm_batter[normalize(aliased_name)]
            elif nn in norm_batter:
                log_name = norm_batter[nn]
            elif sig_name_b:
                log_name = sig_name_b
            else:
                log_name = player_name
            batter_props = [p for p in props if p["stat"] in ("Hits+Runs+RBIs", "Total Bases")]
            card = build_batter_card(log_name, batter_props, batter_logs_by_name, b_proj)
            card["name"] = player_name
            cards.append(card)

    # Sort: pitchers first, then batters, each by highest hit rate
    def sort_key(c):
        best_hr = max((p["hit_rate_all"] for p in c["props"]), default=0)
        return (0 if c["type"] == "pitcher" else 1, -best_hr)

    # Attach park factor and venue to each card
    for card in cards:
        home = home_map.get(card["team"], card["team"])
        pf_data = park_factors.get(home, {})
        card["venue"] = pf_data.get("venue", "")
        card["park_factor"] = pf_data.get("pf_r", 1.0)

    cards.sort(key=sort_key)

    output = {
        "generated_at": __import__("datetime").datetime.now(__import__("datetime").timezone.utc).isoformat(),
        "total_props": sum(len(c["props"]) for c in cards),
        "cards": cards,
    }

    out_path = os.path.join(PUBLIC_DATA, "prizepicks_props.json")

    # Guard: don't overwrite a richer snapshot with a smaller one
    # (e.g. CI odds scraper didn't find batter lines this run)
    if os.path.exists(out_path):
        try:
            with open(out_path) as f:
                prev = json.load(f)
            prev_cards = len(prev.get("cards", []))
            if prev_cards > len(cards) and len(cards) > 0:
                print(f"⚠ Skipping write: existing file has {prev_cards} cards vs {len(cards)} new — keeping richer snapshot")
                return
        except Exception:
            pass

    with open(out_path, "w") as f:
        json.dump(output, f, indent=2)
    print(f"Wrote {len(cards)} player cards ({output['total_props']} props) to {out_path}")

if __name__ == "__main__":
    main()
